### ISSUE TITLE
002_timescaledb_tune error

### ISSUE THREAD

**Issue by le-andreazevedo** [Expaso/hassos-addon-timescaledb#1]
Hi,

I'm running HASSio in a RPi 3 Model.

After install timescaledb and try to start it, it stops immediately.

Logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: TimescaleDB
 An open-source database built on PostgreSQL for analyzing time-series data with the power and convenience of SQL
-----------------------------------------------------------
 Add-on version: 0.2.1
 You are running the latest version of this add-on.
parse error: Expected string key before ':' at line 1, column 4
[12:43:08] ERROR: Unknown HTTP error occured
 System:   (aarch64 / raspberrypi3-64)
 Home Assistant Core: 0.109.4
 Home Assistant Supervisor: 222
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:43:12] INFO: Using existing PostgreSQL installation..
[12:43:12] INFO: done
[12:43:12] INFO: Tuning resources..
./run: line 45: /usr/share/timescaledb/002_timescaledb_tune.sh: Permission denied
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal
```

My config:
```
databases:
  - homeassistant2
timescale_enabled:
  - homeassistant2
timescaledb:
  telemetry: basic
  maxmemory: 512MB
  maxcpus: '4'
```

**Comment by Expaso** [comment]
Hi @le-andreazevedo , Thanks! I did nog expect any feedback so soon! Thanks!
I saw the issue myself just yet, and am fixing it now.

**Comment by Expaso** [comment]
It seems a cross-compile issue in the CI/CD.
In the meantime, I have temporarily disabled auto-tuning, so you can start using the add-on, while I fix this issue.

Can you please give feedback if the rest works OK?

**Comment by Expaso** [comment]
Fixed in 1.0.2.

**Comment by le-andreazevedo** [comment]
Hi @Expaso,

Found a bug in pgAdmin 4 plugin; "OPEN WEB UI" is not redirecting correctly. I have to introduce the port manually in the url to get into de pdAdmin

Question:
Do I need any additional config to get HASS data recorded in timescaleDB?

Best regards,
Andre Azevedo

**Comment by Expaso** [comment]
"Found a bug in pgAdmin 4 plugin; "OPEN WEB UI" is not redirecting correctly. I have to introduce the port manually in the url to get into de pgAdmin"
- Are you using a port-numer after your URL of your hassio installation?

"Do I need any additional config to get HASS data recorded in timescaleDB?"
- Yes. It's just the database server with timescale itself.
For data inflow from HA you can use this:
https://community.home-assistant.io/t/custom-component-long-time-state-storage-ltss-utilizing-timescaledb/155047

I think you also can install it with HACS.

**Comment by Expaso** [comment]
@le-andreazevedo "Open Web UI" is now fixed in v1.0.1. (CD is running, update should be live within 30 mins)

**Comment by le-andreazevedo** [comment]
Hi @Expaso,

v1.0.1 not showing in Add-on Store. Still showing v1.0.0 as the last available.

I'm not being able to inflow data to DB. HASS warning about config error, my LTSS config:
```
ltss: 
    db_url: "postgresql://postgres:homeassistant@10.110.44.51:5432/homeassistant"
```

**Comment by le-andreazevedo** [comment]
Hi @Expaso,

Can you help me about my last comment?

Thanks in advance

**Comment by Expaso** [comment]
Hi @le-andreazevedo :  The LTSS error is a problem with ltss itself.  I've already commented on their issue.
In the meantime, you could edit `/config/custom_components/ltss/__init__.py ` , and replace the CONFIG_SCHEMA block on line 64 with this:
```
CONFIG_SCHEMA = vol.Schema(
    {
		DOMAIN: FILTER_SCHEMA.extend(
			{
				vol.Required(CONF_DB_URL): cv.string,
			}
		)
    },
    extra=vol.ALLOW_EXTRA,
)
```

That should fix the config-validation error.

**Comment by le-andreazevedo** [comment]
everything fixed with your recent updates

Thanks a lot

**Comment by Expaso** [comment]
You're welcome, Happy querying!!

I saw that the LTSS author also released the update with above code in HACS.

ProTip: The LTSS extention stores the JSON-body in a text-column, while Postgress can bet setup to use the JSONB data type on that column.
(using something like:
ALTER TABLE ltss
ALTER COLUMN attrobutes TYPE JSON USING attributes::jsonb;
)

This allows you to create an index on the JSON, should you need it.

See also: https://github.com/freol35241/ltss/issues/6
